export { default as HomePage } from "../Public/HomePage/index";
export { default as TaskPage } from "../Public/Tasks/TaskPage";
export { default as ReferralPage } from "../Public/ReferralPage";
export { default as RegisterPage } from "../Public/Auth/RegisterPage";
export { default as LoginPage } from "../Public/Auth/LoginPage";
export { default as VerifyOtp } from "../Public/Auth/VerifyOtp";
export { default as ResetPassword } from "../Public/Auth/ResetPassword";
export { default as ForgotPassword } from "../Public/Auth/ForgotPassword";
export { default as UnauthorizedPage } from "../Public/Unauthorized";
